CREATE TABLE orders (
    id SERIAL PRIMARY KEY NOT NULL,
    user_id BIGINT REFERENCES users(id) NOT NULL,
    number VARCHAR(255) UNIQUE NOT NULL,
    status VARCHAR(10) NOT NULL DEFAULT 'NEW',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_orders_status ON orders(status);